import 'erp_role.dart';
import 'permissions.dart';

/// Maps each [ErpRole] to its default [PermissionSet].
class RolePermissionMatrix {
  const RolePermissionMatrix._();

  static PermissionSet permissionsFor(ErpRole role) {
    return PermissionSet.from(_permissionsForRole[role] ?? const {});
  }

  static const Map<ErpRole, Set<Permission>> _permissionsForRole = {
    ErpRole.superAdmin: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.manageAdmissions,
      Permission.approveAdmissions,
      Permission.viewFinance,
      Permission.manageFinance,
      Permission.approveRefunds,
      Permission.viewSis,
      Permission.manageSis,
      Permission.viewManagement,
      Permission.manageManagement,
      Permission.viewTransport,
      Permission.manageTransport,
      Permission.viewHr,
      Permission.manageHr,
      Permission.viewHostel,
      Permission.manageHostel,
      Permission.viewLibrary,
      Permission.manageLibrary,
      Permission.viewInventory,
      Permission.manageInventory,
      Permission.viewAlumni,
      Permission.manageAlumni,
      Permission.viewControlCenter,
      Permission.manageControlCenter,
    },
    ErpRole.schoolAdmin: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.manageAdmissions,
      Permission.approveAdmissions,
      Permission.viewFinance,
      Permission.manageFinance,
      Permission.approveRefunds,
      Permission.viewSis,
      Permission.manageSis,
      Permission.viewManagement,
      Permission.manageManagement,
      Permission.viewTransport,
      Permission.manageTransport,
      Permission.viewHr,
      Permission.manageHr,
      Permission.viewHostel,
      Permission.manageHostel,
      Permission.viewLibrary,
      Permission.manageLibrary,
      Permission.viewInventory,
      Permission.manageInventory,
      Permission.viewAlumni,
      Permission.manageAlumni,
    },
    ErpRole.principal: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.manageAdmissions,
      Permission.approveAdmissions,
      Permission.viewFinance,
      Permission.viewSis,
      Permission.manageSis,
      Permission.viewManagement,
      Permission.manageManagement,
      Permission.viewLibrary,
      Permission.viewHr,
      Permission.viewAlumni,
    },
    ErpRole.management: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.viewFinance,
      Permission.manageFinance,
      Permission.viewSis,
      Permission.viewManagement,
      Permission.manageManagement,
      Permission.viewTransport,
      Permission.viewHr,
      Permission.viewHostel,
      Permission.viewLibrary,
      Permission.viewInventory,
      Permission.viewAlumni,
    },
    ErpRole.financeAdmin: {
      Permission.viewAdminHub,
      Permission.viewFinance,
      Permission.manageFinance,
      Permission.approveRefunds,
    },
    ErpRole.admissionsCounselor: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.manageAdmissions,
      Permission.viewSis,
    },
    ErpRole.transportManager: {
      Permission.viewAdminHub,
      Permission.viewTransport,
      Permission.manageTransport,
    },
    ErpRole.hostelManager: {
      Permission.viewAdminHub,
      Permission.viewHostel,
      Permission.manageHostel,
    },
    ErpRole.librarian: {
      Permission.viewAdminHub,
      Permission.viewLibrary,
      Permission.manageLibrary,
    },
    ErpRole.inventoryManager: {
      Permission.viewAdminHub,
      Permission.viewInventory,
      Permission.manageInventory,
    },
    ErpRole.teacher: {},
    ErpRole.parent: {},
    ErpRole.student: {},
  };
}
