import 'erp_role.dart';
import 'permissions.dart';

/// Maps each [ErpRole] to its default [PermissionSet].
class RolePermissionMatrix {
  const RolePermissionMatrix._();

  /// Roles that are NOT staff and therefore never self-check-in (O5/O4).
  ///
  /// [ErpRole.unsupported] is listed here for a different reason: it must receive
  /// the empty set, and `_withStaffAttendance` would otherwise hand every
  /// non-parent/student role `markStaffAttendance` — including the fail-closed
  /// sentinel. A role the app cannot render must grant *nothing at all*
  /// (JOURNEY-002).
  ///
  /// BUS-013: driver/attendant are transport FIELD roles, not school staff.
  /// They must not inherit the staff self-check-in grant — staff attendance is a
  /// geofenced+face-verified school-premises flow, which is meaningless for
  /// someone whose whole shift is on a bus.
  static const Set<ErpRole> _nonStaffRoles = {
    ErpRole.parent,
    ErpRole.student,
    ErpRole.driver,
    ErpRole.attendant,
    ErpRole.unsupported,
  };

  static PermissionSet permissionsFor(ErpRole role) {
    return PermissionSet.from(_withStaffAttendance(role, _permissionsForRole[role] ?? const {}));
  }

  /// Union of the default permissions across every role in [roles].
  /// A multi-hat user (e.g. Teacher + Inventory Manager) gets both sets.
  static PermissionSet permissionsForRoles(Iterable<ErpRole> roles) {
    final union = <Permission>{};
    for (final role in roles) {
      union.addAll(_withStaffAttendance(role, _permissionsForRole[role] ?? const {}));
    }
    return PermissionSet.from(union);
  }

  /// O5: every staff persona (everyone except parent/student) may self check-in
  /// via device biometric. Granted here — and seeded server-side in
  /// `20260818000000_staff_face_id_attendance.sql` — rather than hand-listed in
  /// 13 role sets, so a new staff role inherits it automatically.
  static Set<Permission> _withStaffAttendance(ErpRole role, Set<Permission> base) {
    if (_nonStaffRoles.contains(role)) return base;
    return {...base, Permission.markStaffAttendance};
  }

  static const Map<ErpRole, Set<Permission>> _permissionsForRole = {
    ErpRole.superAdmin: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.manageAdmissions,
      Permission.approveAdmissions,
      Permission.viewFinance,
      Permission.manageFinance,
      Permission.approveRefunds,
      Permission.viewSis,
      Permission.manageSis,
      Permission.viewManagement,
      Permission.manageManagement,
      // PRA-P1-17 school calendar (seeded server-side).
      Permission.viewSchoolCalendar,
      Permission.manageSchoolCalendar,
      Permission.manageWorkflowAutomation,
      Permission.viewTransport,
      Permission.manageTransport,
      Permission.viewHr,
      Permission.manageHr,
      Permission.viewHostel,
      Permission.manageHostel,
      Permission.viewLibrary,
      Permission.manageLibrary,
      Permission.viewInventory,
      Permission.manageInventory,
      Permission.viewAlumni,
      Permission.manageAlumni,
      Permission.viewControlCenter,
      Permission.manageControlCenter,
      Permission.viewDirectorPortal,
      Permission.manageDirectorPortal,
      Permission.viewOrganizationIntelligence,
      // SA-1 (MJ-L5): branch/franchise platform-ops permissions removed — no
      // server migration seeds them, so granting them client-side only
      // surfaced mock-backed tiles in the offline local-matrix fallback.
      Permission.viewOnboarding,
      Permission.manageOnboarding,
      Permission.viewAiCopilot,
      Permission.runAiCopilot,
      Permission.viewAcademicTimetable,
      Permission.manageAcademicTimetable,
      Permission.publishAcademicTimetable,
      Permission.viewAnalytics,
      Permission.viewSchoolHealth,
      Permission.viewEducation,
      Permission.manageEducation,
      Permission.approveEducation,
      Permission.viewExams,
      Permission.manageExams,
      Permission.viewStudentRisk,
      Permission.generateIntelligence,
      Permission.viewHomeworkIntelligence,
      Permission.manageHomeworkIntelligence,
      Permission.viewStudentSuccessIntelligence,
      Permission.viewExamIntelligence,
      Permission.manageExamMarks,
      Permission.submitExamResults,
      Permission.verifyExamResults,
      Permission.moderateExamMarks,
      Permission.approveExamResults,
      Permission.publishExamResults,
      Permission.viewAttendance,
      Permission.approveAttendanceCorrection,
      Permission.approveStudentLeave,
      Permission.approveStaffLeave,
      Permission.approveStaffAttendance,
      Permission.approveClearanceWaiver,
      Permission.approveFeeConcession,
      Permission.approveFeeStructure,
      Permission.approvePurchaseOrder,
      Permission.viewStudent360,
      Permission.viewEmployees,
      Permission.manageEmployees,
      Permission.viewInventoryDistribution,
      Permission.manageInventoryDistribution,
      Permission.viewParentExperience,
      Permission.viewEmployeeIntelligence,
      Permission.viewOperationsHub,
      Permission.viewSchoolMemories,
      Permission.manageSchoolMemories,
      Permission.viewAchievementPromotion,
      Permission.manageAchievementPromotion,
      Permission.approveAchievementPromotion,
      Permission.viewSchoolSetup,
      Permission.manageSchoolSetup,
      Permission.viewDynamicWidgets,
      Permission.manageDynamicWidgets,
      Permission.viewTeacherAssistant,
      Permission.manageTeacherAssistant,
      Permission.viewParentInsights,
      Permission.viewPrincipalCommand,
      Permission.viewGrowthPlatform,
      Permission.manageGrowthPlatform,
      Permission.viewSubjects,
      Permission.manageSubjects,
      Permission.viewLessonLogs,
      Permission.manageLessonLogs,
      Permission.manageTimetableAutomation,
      Permission.viewSchoolBranding,
      Permission.manageSchoolBranding,
      Permission.viewWhatsAppProvider,
      Permission.manageWhatsAppProvider,
      Permission.managePlatformWhatsApp,
      Permission.viewSubjectAssignments,
      Permission.manageSubjectAssignments,
      Permission.viewLessonAnalytics,
      Permission.viewTimetableOptimization,
      Permission.viewCommunicationDelivery,
      Permission.manageCommunication,
      Permission.manageCommunicationTemplates,
      Permission.viewPilotDashboard,
      Permission.viewCommunicationAnalytics,
      Permission.viewTeacherEffectiveness,
      Permission.manageSyllabus,
      Permission.viewAcademicProgress,
      Permission.manageAcademicProgress,
      Permission.managePlatformProviders,
      Permission.viewPlatformUsage,
      Permission.managePlatformVault,
      Permission.managePlatformFeatures,
      Permission.manageAcademicRooms,
      Permission.viewParentAcademicSummary,
      Permission.viewFinanceIntelligence,
      Permission.viewFinanceExecutiveDashboard,
      Permission.viewInventoryIntelligence,
      Permission.manageAssetLifecycle,
      Permission.manageProcurementWorkflow,
      // SA-1 (MJ-L5): multi-school-operations permissions removed — unseeded
      // server-side; client grant only surfaced the mock-backed portfolio.
      Permission.viewOrganizationBuilder,
      Permission.manageOrganizationBuilder,
      // SA-1 (MJ-L5): platform-operations permissions removed — unseeded
      // server-side (GET /platform-operations/observability is 404 live).
      Permission.viewIndustryFramework,
      Permission.manageIndustryFramework,
      Permission.viewHealthcare,
      Permission.manageHealthcare,
      Permission.viewSalonBusiness,
      Permission.manageSalonBusiness,
      Permission.viewRestaurantHospitality,
      Permission.manageRestaurantHospitality,
      Permission.viewAccommodation,
      Permission.manageAccommodation,
      // SA-1 (MJ-L5): white-label-platform permissions removed — unseeded
      // server-side; client grant only surfaced the mock-backed branding UI.
      // PRC-A Batch 3 (20260888): AI credit wallet. manageAiCredits is
      // superAdmin ONLY — a tenant topping up its own wallet at will is the
      // same as having no wallet.
      Permission.viewAiWallet,
      Permission.manageAiCredits,
      // PRC-A Batch 4 (20260889): storage quota. superAdmin is named alongside
      // organizationOwner/organizationAdmin/management in the seeding.
      Permission.viewStorageQuota,
    },
    ErpRole.schoolAdmin: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.manageAdmissions,
      Permission.approveAdmissions,
      Permission.viewFinance,
      Permission.manageFinance,
      Permission.approveRefunds,
      Permission.viewFinanceIntelligence,
      Permission.viewFinanceExecutiveDashboard,
      Permission.viewSis,
      Permission.manageSis,
      Permission.viewManagement,
      Permission.manageManagement,
      // PRA-P1-17 school calendar (seeded server-side).
      Permission.viewSchoolCalendar,
      Permission.manageSchoolCalendar,
      Permission.viewDirectorPortal,
      Permission.manageDirectorPortal,
      Permission.manageWorkflowAutomation,
      Permission.viewTransport,
      Permission.manageTransport,
      Permission.viewHr,
      Permission.manageHr,
      Permission.viewHostel,
      Permission.manageHostel,
      Permission.viewLibrary,
      Permission.manageLibrary,
      Permission.viewInventory,
      Permission.manageInventory,
      Permission.viewInventoryIntelligence,
      Permission.manageAssetLifecycle,
      Permission.manageProcurementWorkflow,
      Permission.viewMultiSchoolOperations,
      Permission.manageMultiSchoolOperations,
      Permission.viewOrganizationBuilder,
      Permission.manageOrganizationBuilder,
      // Non-school verticals / platform / white-label removed (UX Batch 1,
      // Step 3 — least privilege; superAdmin remains the platform owner).
      Permission.viewAlumni,
      Permission.manageAlumni,
      Permission.viewOnboarding,
      Permission.manageOnboarding,
      Permission.viewOrganizationIntelligence,
      Permission.viewBranchOperations,
      Permission.manageBranchOperations,
      Permission.viewFranchiseOperations,
      Permission.manageFranchiseOperations,
      Permission.viewAiCopilot,
      Permission.runAiCopilot,
      Permission.viewAcademicTimetable,
      Permission.manageAcademicTimetable,
      Permission.publishAcademicTimetable,
      Permission.viewAnalytics,
      Permission.viewSchoolHealth,
      Permission.viewEducation,
      Permission.manageEducation,
      Permission.approveEducation,
      Permission.viewExams,
      Permission.manageExams,
      Permission.viewStudentRisk,
      Permission.generateIntelligence,
      Permission.viewHomeworkIntelligence,
      Permission.manageHomeworkIntelligence,
      Permission.viewStudentSuccessIntelligence,
      Permission.viewExamIntelligence,
      Permission.manageExamMarks,
      Permission.submitExamResults,
      Permission.verifyExamResults,
      Permission.moderateExamMarks,
      Permission.approveExamResults,
      Permission.publishExamResults,
      Permission.viewAttendance,
      Permission.approveAttendanceCorrection,
      Permission.approveStudentLeave,
      Permission.approveStaffLeave,
      Permission.approveStaffAttendance,
      Permission.approveClearanceWaiver,
      Permission.approveFeeConcession,
      Permission.approveFeeStructure,
      Permission.approvePurchaseOrder,
      Permission.viewStudent360,
      Permission.viewEmployees,
      Permission.manageEmployees,
      Permission.viewInventoryDistribution,
      Permission.manageInventoryDistribution,
      Permission.viewEmployeeIntelligence,
      Permission.viewOperationsHub,
      Permission.viewSchoolMemories,
      Permission.manageSchoolMemories,
      Permission.viewAchievementPromotion,
      Permission.manageAchievementPromotion,
      Permission.approveAchievementPromotion,
      Permission.viewSchoolSetup,
      Permission.manageSchoolSetup,
      Permission.viewDynamicWidgets,
      Permission.manageDynamicWidgets,
      Permission.viewTeacherAssistant,
      Permission.manageTeacherAssistant,
      Permission.viewParentInsights,
      Permission.viewPrincipalCommand,
      Permission.viewGrowthPlatform,
      Permission.manageGrowthPlatform,
      Permission.viewSubjects,
      Permission.manageSubjects,
      Permission.viewLessonLogs,
      Permission.manageLessonLogs,
      Permission.manageTimetableAutomation,
      Permission.viewSchoolBranding,
      Permission.manageSchoolBranding,
      Permission.viewWhatsAppProvider,
      Permission.viewSubjectAssignments,
      Permission.manageSubjectAssignments,
      Permission.viewLessonAnalytics,
      Permission.viewTimetableOptimization,
      Permission.viewCommunicationDelivery,
      Permission.manageCommunication,
      Permission.manageCommunicationTemplates,
      Permission.viewPilotDashboard,
      Permission.viewCommunicationAnalytics,
      Permission.viewTeacherEffectiveness,
      Permission.manageSyllabus,
      Permission.viewAcademicProgress,
      Permission.manageAcademicProgress,
      Permission.manageAcademicRooms,
      Permission.viewParentAcademicSummary,
      // PRC-A Batch 3 (20260888): schoolAdmin is the client stand-in for the
      // server's organizationOwner + organizationAdmin roles (see
      // viewOrganizationBuilder / viewDirectorPortal above for precedent).
      Permission.viewAiWallet,
      // PRC-A Batch 4 (20260889): storage quota — same schoolAdmin stand-in.
      Permission.viewStorageQuota,
    },
    ErpRole.principal: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.manageAdmissions,
      Permission.approveAdmissions,
      Permission.viewFinance,
      Permission.viewFinanceExecutiveDashboard,
      Permission.viewInventory,
      Permission.viewInventoryIntelligence,
      Permission.viewSis,
      Permission.manageSis,
      Permission.viewManagement,
      Permission.manageManagement,
      // PRA-P1-17 school calendar (seeded server-side).
      Permission.viewSchoolCalendar,
      Permission.manageSchoolCalendar,
      Permission.viewTransport,
      Permission.viewHostel,
      Permission.viewDirectorPortal,
      Permission.manageDirectorPortal,
      Permission.manageWorkflowAutomation,
      Permission.viewLibrary,
      Permission.viewHr,
      Permission.viewAlumni,
      Permission.viewOnboarding,
      Permission.manageOnboarding,
      Permission.viewOrganizationIntelligence,
      Permission.viewBranchOperations,
      Permission.manageBranchOperations,
      Permission.viewFranchiseOperations,
      Permission.manageFranchiseOperations,
      Permission.viewAiCopilot,
      Permission.runAiCopilot,
      Permission.viewAcademicTimetable,
      Permission.manageAcademicTimetable,
      Permission.publishAcademicTimetable,
      Permission.viewAnalytics,
      Permission.viewSchoolHealth,
      Permission.viewEducation,
      Permission.manageEducation,
      Permission.approveEducation,
      Permission.viewExams,
      Permission.manageExams,
      Permission.viewStudentRisk,
      Permission.generateIntelligence,
      Permission.viewHomeworkIntelligence,
      Permission.manageHomeworkIntelligence,
      Permission.viewStudentSuccessIntelligence,
      Permission.viewExamIntelligence,
      Permission.manageExamMarks,
      Permission.submitExamResults,
      Permission.verifyExamResults,
      Permission.moderateExamMarks,
      Permission.approveExamResults,
      Permission.publishExamResults,
      Permission.viewAttendance,
      Permission.approveAttendanceCorrection,
      Permission.approveStudentLeave,
      Permission.approveStaffLeave,
      Permission.approveStaffAttendance,
      Permission.approveClearanceWaiver,
      Permission.approveFeeConcession,
      Permission.approveFeeStructure,
      Permission.approvePurchaseOrder,
      Permission.viewStudent360,
      Permission.viewEmployees,
      Permission.manageEmployees,
      Permission.viewInventoryDistribution,
      Permission.manageInventoryDistribution,
      Permission.viewEmployeeIntelligence,
      Permission.viewOperationsHub,
      Permission.viewSchoolMemories,
      Permission.manageSchoolMemories,
      Permission.viewAchievementPromotion,
      Permission.manageAchievementPromotion,
      Permission.approveAchievementPromotion,
      Permission.viewSchoolSetup,
      Permission.manageSchoolSetup,
      Permission.viewDynamicWidgets,
      Permission.manageDynamicWidgets,
      Permission.viewTeacherAssistant,
      Permission.viewParentInsights,
      Permission.viewPrincipalCommand,
      Permission.viewGrowthPlatform,
      Permission.manageGrowthPlatform,
      Permission.viewSubjects,
      Permission.manageSubjects,
      Permission.viewLessonLogs,
      Permission.manageTimetableAutomation,
      Permission.viewSchoolBranding,
      Permission.manageSchoolBranding,
      Permission.viewWhatsAppProvider,
      Permission.viewSubjectAssignments,
      Permission.manageSubjectAssignments,
      Permission.viewLessonAnalytics,
      Permission.viewTimetableOptimization,
      Permission.viewCommunicationDelivery,
      Permission.manageCommunication,
      Permission.manageCommunicationTemplates,
      Permission.viewPilotDashboard,
      Permission.viewCommunicationAnalytics,
      Permission.viewTeacherEffectiveness,
      Permission.manageSyllabus,
      Permission.viewAcademicProgress,
      Permission.manageAcademicProgress,
      Permission.manageAcademicRooms,
      Permission.viewParentAcademicSummary,
    },
    ErpRole.vicePrincipal: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.manageAdmissions,
      Permission.approveAdmissions,
      Permission.viewFinance,
      Permission.viewFinanceExecutiveDashboard,
      Permission.viewInventory,
      Permission.viewInventoryIntelligence,
      Permission.viewSis,
      Permission.manageSis,
      Permission.viewManagement,
      Permission.manageManagement,
      // PRA-P1-17 school calendar (seeded server-side).
      Permission.viewSchoolCalendar,
      Permission.manageSchoolCalendar,
      Permission.viewTransport,
      Permission.viewHostel,
      Permission.viewDirectorPortal,
      Permission.manageDirectorPortal,
      Permission.manageWorkflowAutomation,
      Permission.viewLibrary,
      Permission.viewHr,
      Permission.viewAlumni,
      Permission.viewOnboarding,
      Permission.manageOnboarding,
      Permission.viewOrganizationIntelligence,
      Permission.viewBranchOperations,
      Permission.manageBranchOperations,
      Permission.viewFranchiseOperations,
      Permission.manageFranchiseOperations,
      Permission.viewAiCopilot,
      Permission.runAiCopilot,
      Permission.viewAcademicTimetable,
      Permission.manageAcademicTimetable,
      Permission.publishAcademicTimetable,
      Permission.viewAnalytics,
      Permission.viewSchoolHealth,
      Permission.viewEducation,
      Permission.manageEducation,
      Permission.approveEducation,
      Permission.viewExams,
      Permission.manageExams,
      Permission.viewStudentRisk,
      Permission.generateIntelligence,
      Permission.viewHomeworkIntelligence,
      Permission.manageHomeworkIntelligence,
      Permission.viewStudentSuccessIntelligence,
      Permission.viewExamIntelligence,
      Permission.manageExamMarks,
      Permission.submitExamResults,
      Permission.verifyExamResults,
      Permission.moderateExamMarks,
      Permission.approveExamResults,
      Permission.publishExamResults,
      Permission.viewAttendance,
      Permission.approveAttendanceCorrection,
      Permission.approveStudentLeave,
      Permission.approveStaffLeave,
      Permission.approveStaffAttendance,
      Permission.approveClearanceWaiver,
      Permission.approveFeeConcession,
      Permission.approveFeeStructure,
      Permission.approvePurchaseOrder,
      Permission.viewStudent360,
      Permission.viewEmployees,
      Permission.manageEmployees,
      Permission.viewInventoryDistribution,
      Permission.manageInventoryDistribution,
      Permission.viewEmployeeIntelligence,
      Permission.viewOperationsHub,
      Permission.viewSchoolMemories,
      Permission.manageSchoolMemories,
      Permission.viewAchievementPromotion,
      Permission.manageAchievementPromotion,
      Permission.approveAchievementPromotion,
      Permission.viewSchoolSetup,
      Permission.manageSchoolSetup,
      Permission.viewDynamicWidgets,
      Permission.manageDynamicWidgets,
      Permission.viewTeacherAssistant,
      Permission.viewParentInsights,
      Permission.viewPrincipalCommand,
      Permission.viewGrowthPlatform,
      Permission.manageGrowthPlatform,
      Permission.viewSubjects,
      Permission.manageSubjects,
      Permission.viewLessonLogs,
      Permission.manageTimetableAutomation,
      Permission.viewSchoolBranding,
      Permission.manageSchoolBranding,
      Permission.viewWhatsAppProvider,
      Permission.viewSubjectAssignments,
      Permission.manageSubjectAssignments,
      Permission.viewLessonAnalytics,
      Permission.viewTimetableOptimization,
      Permission.viewCommunicationDelivery,
      Permission.manageCommunication,
      Permission.manageCommunicationTemplates,
      Permission.viewPilotDashboard,
      Permission.viewCommunicationAnalytics,
      Permission.viewTeacherEffectiveness,
      Permission.manageSyllabus,
      Permission.viewAcademicProgress,
      Permission.manageAcademicProgress,
      Permission.manageAcademicRooms,
      Permission.viewParentAcademicSummary,
    },
    ErpRole.management: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.viewFinance,
      Permission.manageFinance,
      Permission.viewSis,
      Permission.viewManagement,
      Permission.manageManagement,
      Permission.viewDirectorPortal,
      Permission.manageDirectorPortal,
      Permission.manageWorkflowAutomation,
      Permission.viewTransport,
      Permission.viewHr,
      Permission.manageHr,
      Permission.submitStaffLeave,
      Permission.viewHostel,
      Permission.viewLibrary,
      Permission.viewInventory,
      Permission.viewAlumni,
      Permission.viewOrganizationIntelligence,
      Permission.viewBranchOperations,
      Permission.manageBranchOperations,
      Permission.viewFranchiseOperations,
      Permission.manageFranchiseOperations,
      Permission.viewAiCopilot,
      Permission.runAiCopilot,
      Permission.viewAnalytics,
      Permission.viewSchoolHealth,
      Permission.viewStudentRisk,
      Permission.viewHomeworkIntelligence,
      Permission.viewStudentSuccessIntelligence,
      Permission.viewExamIntelligence,
      Permission.manageExamMarks,
      Permission.submitExamResults,
      Permission.verifyExamResults,
      Permission.moderateExamMarks,
      Permission.approveExamResults,
      Permission.publishExamResults,
      Permission.viewAttendance,
      Permission.approveAttendanceCorrection,
      Permission.approveStudentLeave,
      Permission.approveStaffLeave,
      Permission.approveStaffAttendance,
      Permission.approveClearanceWaiver,
      Permission.approveFeeConcession,
      Permission.approveFeeStructure,
      Permission.approvePurchaseOrder,
      Permission.viewStudent360,
      Permission.viewEmployees,
      Permission.viewInventoryDistribution,
      Permission.viewOperationsHub,
      Permission.viewSchoolMemories,
      Permission.viewAchievementPromotion,
      Permission.viewMultiSchoolOperations,
      Permission.manageMultiSchoolOperations,
      Permission.viewOrganizationBuilder,
      Permission.manageOrganizationBuilder,
      // Non-school verticals / platform / white-label removed (UX Batch 1, Step 3
      // — least privilege; a school role never administers Salon/Restaurant/
      // Healthcare/Accommodation/Industry/WhiteLabel/PlatformOps). superAdmin
      // remains the platform/multi-industry owner.
      // PRC-A Batch 3 (20260888): management is explicitly named alongside
      // superAdmin/organizationOwner/organizationAdmin in the seeding.
      Permission.viewAiWallet,
      // PRC-A Batch 4 (20260889): storage quota — same seeding precedent.
      Permission.viewStorageQuota,
    },
    ErpRole.financeAdmin: {
      Permission.viewAdminHub,
      Permission.viewFinance,
      Permission.manageFinance,
      Permission.approveRefunds,
      Permission.assignScholarship,
      Permission.approveFeeConcession,
      Permission.approveFeeStructure,
      Permission.submitFeeStructureForApproval,
      Permission.viewFinanceIntelligence,
      Permission.viewFinanceExecutiveDashboard,
      Permission.viewAiCopilot,
      Permission.runAiCopilot,
    },
    ErpRole.admissionsCounselor: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.manageAdmissions,
      Permission.viewSis,
      Permission.viewAiCopilot,
      Permission.runAiCopilot,
    },
    ErpRole.transportManager: {
      Permission.viewAdminHub,
      Permission.viewTransport,
      Permission.manageTransport,
    },
    // BUS-013 — driver. Deliberately minimal: no admin hub, no transport
    // module read, no other driver's trip. Everything is scoped to TODAY'S
    // assigned trip and enforced in RLS.
    ErpRole.driver: {
      Permission.viewOwnTransportTrip,
      Permission.operateTransportTrip,
      Permission.recordTransportBoarding,
      Permission.raiseTransportSos,
    },
    // BUS-053 — attendant. Same visibility as the driver MINUS trip control:
    // the person who marks boarding is not the person who starts the bus.
    ErpRole.attendant: {
      Permission.viewOwnTransportTrip,
      Permission.recordTransportBoarding,
      Permission.raiseTransportSos,
    },
    ErpRole.hostelManager: {
      Permission.viewAdminHub,
      Permission.viewHostel,
      Permission.manageHostel,
    },
    ErpRole.librarian: {
      Permission.viewAdminHub,
      Permission.viewLibrary,
      Permission.manageLibrary,
    },
    ErpRole.teacher: {
      // PRA-P1-17 school calendar (seeded server-side).
      Permission.viewSchoolCalendar,
      Permission.viewEducation,
      Permission.manageEducation,
      Permission.viewExams,
      Permission.viewStudentRisk,
      Permission.generateIntelligence,
      Permission.viewHomeworkIntelligence,
      Permission.manageHomeworkIntelligence,
      Permission.viewStudentSuccessIntelligence,
      Permission.viewExamIntelligence,
      Permission.manageExamMarks,
      Permission.submitExamResults,
      // Wave 5 MJ-M10 — teacher creates & grades homework (server-gated too).
      Permission.manageHomework,
      Permission.markAttendance,
      Permission.viewAttendance,
      Permission.submitAttendanceCorrection,
      // Class teacher approves student leave for their own class (scoped at the
      // action layer to the class-teacher's class).
      Permission.approveStudentLeave,
      Permission.viewStudent360,
      Permission.viewEmployees,
      Permission.viewAchievementPromotion,
      Permission.manageAchievementPromotion,
      Permission.viewTeacherAssistant,
      Permission.manageTeacherAssistant,
      Permission.viewSubjects,
      Permission.viewLessonLogs,
      Permission.manageLessonLogs,
      Permission.viewSubjectAssignments,
      Permission.viewLessonAnalytics,
      Permission.viewAcademicProgress,
      Permission.manageAcademicProgress,
      Permission.viewTeacherEffectiveness,
    },
    ErpRole.inventoryManager: {
      Permission.viewAdminHub,
      Permission.viewInventory,
      Permission.manageInventory,
      Permission.createInventoryPo,
      Permission.approvePurchaseOrder,
      Permission.viewInventoryIntelligence,
      Permission.manageAssetLifecycle,
      Permission.manageProcurementWorkflow,
      Permission.viewInventoryDistribution,
      Permission.manageInventoryDistribution,
    },
    ErpRole.storekeeper: {
      Permission.viewAdminHub,
      Permission.viewInventory,
      Permission.createInventoryPo,
    },
    ErpRole.parent: {
      // BUS-013/BUS-095: a parent may read THEIR OWN child's transport. The
      // parent role previously held no transport permission at all, while the
      // client called a school-scoped endpoint — a guaranteed 403 in the live
      // build. Scope is enforced in RLS, not here (TRANSPORT_DOMAIN_CONTRACT §5).
      Permission.viewChildTransport,
      Permission.viewParentExperience,
      Permission.viewParentInsights,
      Permission.viewParentAcademicSummary,
      Permission.viewAttendance,
      Permission.submitStudentLeave,
      Permission.submitAttendanceCorrection,
    },
    // BUS-013/BUS-101: the student role held an EMPTY permission set, so no
    // student-facing surface was reachable at all. Transport self-view only —
    // never a manifest, never another student.
    ErpRole.student: {
      Permission.viewOwnTransport,
    },

    // ─── JOURNEY-002 · the five seeded school roles ─────────────────────────
    // Each set mirrors the grants the SERVER seeds for that slug, and nothing
    // more. The server stays the real enforcement; these exist so the offline
    // local-matrix fallback and the client's role-keyed gates agree with it
    // instead of inventing access. Sources:
    //   hrManager / officeStaff / classTeacher / coordinator
    //     → 20260608100000_rbac_foundation.sql (+ 20260900000010_office_staff_grants.sql)
    //   healthStaff
    //     → 20260887000000_student_health.sql
    ErpRole.hrManager: {
      Permission.viewAdminHub,
      Permission.viewHr,
      Permission.manageHr,
      // Client/server divergence closed: `20260820000000_staff_attendance_
      // geofence_face_reimpl.sql:181-190` grants `approveStaffAttendance` to
      // exactly {principal, vicePrincipal, schoolAdmin, hrManager, management,
      // superAdmin, organizationOwner, organizationAdmin}. Every one of those
      // that this app maps holds it here — except hrManager did not, so an HR
      // Manager lost the manual-attendance approver queue client-side while the
      // server would have let them decide. Deciding a colleague's attendance
      // record is precisely an HR manager's job, and the server is the
      // authority, so the CLIENT was wrong.
      //
      // `manageSchoolGeofence` is granted to the same eight roles server-side
      // and has NO client [Permission] at all — nothing in `lib/` can express or
      // check it. That is a real gap, but adding an enum value with no consumer
      // would be an invention; it is reported rather than guessed at.
      //
      // The three org-scope roles in that list (organizationOwner,
      // organizationAdmin, and the group-scope schoolGroupDirector) stay
      // deliberately unmapped — see kDeliberatelyUnsupportedServerRoles.
      Permission.approveStaffAttendance,
    },
    ErpRole.officeStaff: {
      Permission.viewAdminHub,
      Permission.viewAdmissions,
      Permission.manageAdmissions,
      Permission.viewSis,
      Permission.viewAcademicTimetable,
    },
    ErpRole.healthStaff: {
      Permission.viewAdminHub,
      Permission.viewStudentHealthRecord,
      Permission.manageStudentHealth,
      Permission.administerStudentMedication,
    },
    ErpRole.classTeacher: {
      Permission.viewAdminHub,
      Permission.viewSis,
      Permission.markAttendance,
      Permission.manageHomework,
      Permission.manageExamMarks,
    },
    ErpRole.coordinator: {
      Permission.viewAdminHub,
      Permission.viewSis,
      Permission.viewAdmissions,
      Permission.manageAdmissions,
      Permission.markAttendance,
      Permission.manageHomework,
      Permission.manageExamMarks,
    },

    // The fail-closed sentinel: an unmapped server role grants NOTHING. Listed
    // explicitly (rather than relying on the `?? const {}` lookup default) so the
    // intent is visible at the point a reader looks for it.
    ErpRole.unsupported: {},
  };
}
