import 'package:flutter/foundation.dart';

@immutable
class OnboardingImportJob {
  const OnboardingImportJob({
    required this.id,
    required this.importType,
    required this.status,
    required this.fileName,
    required this.totalRows,
    required this.validRows,
    required this.invalidRows,
    required this.duplicateRows,
    required this.committedRows,
    this.generatedCount = 0,
  });

  final String id;
  final String importType;
  final String status;
  final String fileName;
  final int totalRows;
  final int validRows;
  final int invalidRows;
  final int duplicateRows;
  final int committedRows;

  /// Number of placeholder students generated by the structure step (Path 2).
  /// Zero for ordinary file imports.
  final int generatedCount;
}

/// Structure capture for placeholder generation (Path 2).
///
/// One class with the sections to create under it.
@immutable
class ClassSectionStructure {
  const ClassSectionStructure({
    required this.classLabel,
    required this.sections,
  });

  final String classLabel;
  final List<SectionSize> sections;

  ClassSectionStructure copyWith({
    String? classLabel,
    List<SectionSize>? sections,
  }) {
    return ClassSectionStructure(
      classLabel: classLabel ?? this.classLabel,
      sections: sections ?? this.sections,
    );
  }

  Map<String, dynamic> toJson() => {
        'classLabel': classLabel,
        'sections': [for (final s in sections) s.toJson()],
      };
}

/// One section + how many placeholder students to seed in it.
@immutable
class SectionSize {
  const SectionSize({
    required this.sectionLabel,
    required this.studentCount,
  });

  final String sectionLabel;
  final int studentCount;

  SectionSize copyWith({String? sectionLabel, int? studentCount}) {
    return SectionSize(
      sectionLabel: sectionLabel ?? this.sectionLabel,
      studentCount: studentCount ?? this.studentCount,
    );
  }

  Map<String, dynamic> toJson() => {
        'sectionLabel': sectionLabel,
        'studentCount': studentCount,
      };
}

@immutable
class OnboardingImportPreviewRow {
  const OnboardingImportPreviewRow({
    required this.rowNumber,
    required this.status,
    required this.errors,
  });

  final int rowNumber;
  final String status;
  final List<String> errors;
}

@immutable
class OnboardingImportPreviewResult {
  const OnboardingImportPreviewResult({
    required this.job,
    required this.preview,
  });

  final OnboardingImportJob job;
  final List<OnboardingImportPreviewRow> preview;
}

@immutable
class OnboardingInvite {
  const OnboardingInvite({
    required this.id,
    required this.inviteType,
    required this.recipientPhone,
    required this.recipientLabel,
    required this.status,
    required this.channel,
    required this.deepLink,
    this.whatsappLink,
  });

  final String id;
  final String inviteType;
  final String recipientPhone;
  final String recipientLabel;
  final String status;
  final String channel;
  final String deepLink;
  final String? whatsappLink;
}

@immutable
class OnboardingDashboardData {
  const OnboardingDashboardData({
    required this.recentJobs,
    required this.pendingInvites,
    required this.totalInvites,
  });

  final List<OnboardingImportJob> recentJobs;
  final int pendingInvites;
  final int totalInvites;
}
