import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'evolution_models.dart';
import '../../theme/spacing.dart';

/// Builds and shares/prints a real PDF sheet for a [ParentInsightSnapshot].
///
/// Replaces the earlier "export preview" stub on the Parent Insights screen so
/// the print/share action produces a genuine, shareable document.
class ParentInsightsPdfService {
  const ParentInsightsPdfService();

  Future<Uint8List> buildInsightPdf(
    ParentInsightSnapshot snapshot, {
    required String schoolName,
    required String childName,
    required String childClass,
  }) async {
    final document = pw.Document();
    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(AksharaSpacing.s6),
        build: (context) => [
          pw.Text(
            schoolName.isEmpty ? 'Parent Insights' : schoolName,
            style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Parent Insights — ${_titleCase(snapshot.period)} summary',
            style: const pw.TextStyle(fontSize: 14),
          ),
          pw.Divider(),
          _kv('Student', childName),
          _kv('Class', childClass),
          _kv('Period', _titleCase(snapshot.period)),
          _kv('Language', _titleCase(snapshot.language)),
          pw.SizedBox(height: 12),
          if (snapshot.progressSummary.isNotEmpty) ...[
            _heading('Progress summary'),
            pw.Text(snapshot.progressSummary),
            pw.SizedBox(height: 12),
          ],
          _bulletSection('Strengths', snapshot.strengths),
          _bulletSection('Areas to improve', snapshot.weaknesses),
          _bulletSection('Attendance', snapshot.attendanceInsights),
          _bulletSection('Homework', snapshot.homeworkInsights),
          _bulletSection('Suggestions', snapshot.improvementSuggestions),
          if (snapshot.teacherRemarksSummary.isNotEmpty) ...[
            _heading('Teacher remarks'),
            pw.Text(snapshot.teacherRemarksSummary),
            pw.SizedBox(height: 12),
          ],
          pw.SizedBox(height: 8),
          pw.Text(
            'Generated by NIKSHA OS — AI-assisted summary based on your child\'s '
            'recent school activity.',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );
    return document.save();
  }

  Future<void> printInsight(Uint8List bytes) async {
    await Printing.layoutPdf(onLayout: (_) async => bytes);
  }

  Future<void> shareInsight({
    required Uint8List bytes,
    required String fileName,
  }) async {
    await Printing.sharePdf(bytes: bytes, filename: fileName);
  }

  pw.Widget _heading(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: AksharaSpacing.s1),
      child: pw.Text(
        text,
        style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
      ),
    );
  }

  pw.Widget _kv(String key, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: AksharaSpacing.s1),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 120,
            child: pw.Text(
              '$key:',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Expanded(child: pw.Text(value.isEmpty ? '—' : value)),
        ],
      ),
    );
  }

  pw.Widget _bulletSection(String title, List<String> items) {
    if (items.isEmpty) return pw.SizedBox();
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _heading(title),
        for (final item in items)
          pw.Bullet(text: item, style: const pw.TextStyle(fontSize: 11)),
        pw.SizedBox(height: 12),
      ],
    );
  }

  String _titleCase(String value) {
    if (value.isEmpty) return value;
    return value
        .split(RegExp(r'[_\s]+'))
        .where((w) => w.isNotEmpty)
        .map((w) => '${w[0].toUpperCase()}${w.substring(1)}')
        .join(' ');
  }
}
