"""Biology genetics on the SAME compositional engine — deterministic (Tier-1) verification.

Mendelian inheritance is rule-based and computable, so it needs no corpus: each item is generated by explicit
Punnett-square ENUMERATION and verified end-to-end by an INDEPENDENT second method (the probability product /
conditional rule, or a full-grid enumeration) — genuinely different computations that must agree. This is core
NEET Biology (a genuine non-quantitative *reasoning* domain that is nonetheless fully deterministic). The engine
(compose.py) and composition machinery (compositions.py) are unchanged; genetics only registers operators +
templates. No AI in the truth path.
"""
from __future__ import annotations

from fractions import Fraction
from typing import Dict

from kie.qie import compose as C
from kie.qie.compose import NUMBER, Operator, Step, close
from kie.qie.compositions import CompositionTemplate, _si, register

GENOTYPE, DIST = "GENOTYPE", "DIST"

# canonical Mendelian traits (textbook — dominant/recessive/letter); no fabrication
TRAITS = [("plant height", "tall", "dwarf", "T"), ("seed shape", "round", "wrinkled", "R"),
          ("seed colour", "yellow", "green", "Y"), ("flower colour", "violet", "white", "V"),
          ("pod shape", "inflated", "constricted", "N")]


def _gametes(gt: str):
    return [gt[0], gt[1]]


def _cross(p1: str, p2: str):
    return tuple(a + b for a in _gametes(p1) for b in _gametes(p2))     # 4 offspring genotypes


def _reg(name, apply, verify, in_types, out_type):
    C.OPERATORS[name] = Operator(name, "GENETICS", "biology", in_types, out_type, apply, verify)


# ── genetics operators ────────────────────────────────────────────────────────────────────────────────
def _pc_verify(ins, out):
    p1, p2 = ins
    g1, g2 = set(_gametes(p1)), set(_gametes(p2))
    return len(out) == 4 and all(len(o) == 2 and o[0] in g1 and o[1] in g2 for o in out)


_reg("punnett_cross", _cross, _pc_verify, (GENOTYPE, GENOTYPE), DIST)
# recessive-phenotype fraction; verified independently as 1 − (dominant fraction), a different partition
_reg("frac_recessive", lambda d: Fraction(sum(o.islower() for o in d), len(d)),
     lambda ins, out: out == 1 - Fraction(sum(not o.islower() for o in ins[0]), len(ins[0])),
     (DIST,), NUMBER)
_reg("frac_dominant", lambda d: Fraction(sum(not o.islower() for o in d), len(d)),
     lambda ins, out: out == 1 - Fraction(sum(o.islower() for o in ins[0]), len(ins[0])),
     (DIST,), NUMBER)
# homozygous-dominant fraction; verified by the genotype-equality count (different predicate)
_reg("frac_homozygous_dominant", lambda d: Fraction(sum(o.isupper() for o in d), len(d)),
     lambda ins, out: out == Fraction(sum(o[0] == o[1] and o[0].isupper() for o in ins[0]), len(ins[0])),
     (DIST,), NUMBER)
_reg("mult_frac", lambda a, b: a * b, lambda ins, out: ins[1] != 0 and out / ins[1] == ins[0],
     (NUMBER, NUMBER), NUMBER)
_reg("div_frac", lambda a, b: a / b, lambda ins, out: out * ins[1] == ins[0], (NUMBER, NUMBER), NUMBER)


# ── GEN-A: monohybrid recessive-phenotype fraction (Punnett vs probability product) ───────────────────
def _mono_setup(seed):
    trait, dom, rec, L = TRAITS[_si(seed + "t", 0, len(TRAITS) - 1)]
    l = L.lower()
    p1, p2 = [(L + l, L + l), (L + l, l + l)][_si(seed + "x", 0, 1)]     # Tt×Tt (→1/4) or Tt×tt (→1/2)
    return {"p1": p1, "p2": p2}, {"p1": p1, "p2": p2, "trait": trait, "dom": dom, "rec": rec, "L": L, "l": l}


def _mono_e2e(env, p):
    pr1 = Fraction(sum(a.islower() for a in p["p1"]), 2)                 # P(recessive allele from parent 1)
    pr2 = Fraction(sum(a.islower() for a in p["p2"]), 2)
    return close(pr1 * pr2, env["ans"])


_GEN_MONO = CompositionTemplate(
    "gen_monohybrid_recessive", "COMPOSE_GEN_MONOHYBRID_RECESSIVE", _mono_setup,
    [Step("dist", "punnett_cross", ("p1", "p2")), Step("ans", "frac_recessive", ("dist",))],
    "ans", _mono_e2e,
    lambda env, p: (f"In pea plants, {p['dom']} ({p['L']}) is dominant over {p['rec']} ({p['l']}). In the cross "
                    f"{p['p1']} × {p['p2']}, the fraction of offspring expected to show the {p['rec']} phenotype is:"),
    lambda env, p: [Fraction(3, 4), Fraction(1, 2), Fraction(1, 16), Fraction(1, 3)],
    subject="Biology", gen_prefix="GENB_",
)


# ── GEN-B: dihybrid both-recessive fraction (product-of-monohybrids vs full 16-grid enumeration) ──────
def _di_setup(seed):
    i = _si(seed + "t1", 0, len(TRAITS) - 1); j = (i + 1 + _si(seed + "t2", 0, len(TRAITS) - 2)) % len(TRAITS)
    t1, t2 = TRAITS[i], TRAITS[j]
    L1, L2 = t1[3], t2[3]
    return {"g1a": L1 + L1.lower(), "g1b": L1 + L1.lower(), "g2a": L2 + L2.lower(), "g2b": L2 + L2.lower()}, \
        {"t1": t1, "t2": t2, "L1": L1, "l1": L1.lower(), "L2": L2, "l2": L2.lower()}


def _di_e2e(env, p):
    both_rec = sum(o1.islower() and o2.islower() for o1 in env["d1"] for o2 in env["d2"])   # full 4×4 grid
    return close(Fraction(both_rec, 16), env["ans"])


_GEN_DI = CompositionTemplate(
    "gen_dihybrid_both_recessive", "COMPOSE_GEN_DIHYBRID_BOTH_RECESSIVE", _di_setup,
    [Step("d1", "punnett_cross", ("g1a", "g1b")), Step("f1", "frac_recessive", ("d1",)),
     Step("d2", "punnett_cross", ("g2a", "g2b")), Step("f2", "frac_recessive", ("d2",)),
     Step("ans", "mult_frac", ("f1", "f2"))],
    "ans", _di_e2e,
    lambda env, p: (f"{p['t1'][1].capitalize()} ({p['L1']}) is dominant over {p['t1'][2]} ({p['l1']}), and "
                    f"{p['t2'][1]} ({p['L2']}) over {p['t2'][2]} ({p['l2']}); the genes assort independently. "
                    f"In the cross {p['L1']}{p['l1']}{p['L2']}{p['l2']} × {p['L1']}{p['l1']}{p['L2']}{p['l2']}, "
                    f"the fraction of offspring showing BOTH recessive traits is:"),
    lambda env, p: [Fraction(9, 16), Fraction(3, 16), Fraction(1, 4), Fraction(1, 8)],
    subject="Biology", gen_prefix="GENB_",
)


# ── GEN-C: conditional — homozygous among dominant phenotype (rule vs subset enumeration) ─────────────
def _cond_setup(seed):
    trait, dom, rec, L = TRAITS[_si(seed + "t", 0, len(TRAITS) - 1)]
    l = L.lower()
    return {"p1": L + l, "p2": L + l}, {"trait": trait, "dom": dom, "rec": rec, "L": L, "l": l}


def _cond_e2e(env, p):
    dom = [o for o in env["dist"] if not o.islower()]
    homo = sum(o.isupper() for o in dom)
    return close(Fraction(homo, len(dom)), env["ans"])                  # among the dominant-phenotype offspring


_GEN_COND = CompositionTemplate(
    "gen_conditional_homozygous", "COMPOSE_GEN_CONDITIONAL_HOMOZYGOUS", _cond_setup,
    [Step("dist", "punnett_cross", ("p1", "p2")), Step("fAA", "frac_homozygous_dominant", ("dist",)),
     Step("fDom", "frac_dominant", ("dist",)), Step("ans", "div_frac", ("fAA", "fDom"))],
    "ans", _cond_e2e,
    lambda env, p: (f"In pea plants, {p['dom']} ({p['L']}) is dominant over {p['rec']} ({p['l']}). In the cross "
                    f"{p['L']}{p['l']} × {p['L']}{p['l']}, among the offspring showing the {p['dom']} phenotype, "
                    f"the fraction that are homozygous ({p['L']}{p['L']}) is:"),
    lambda env, p: [Fraction(1, 4), Fraction(2, 3), Fraction(3, 4), Fraction(1, 2)],
    subject="Biology", gen_prefix="GENB_",
)


TEMPLATES: Dict[str, CompositionTemplate] = {t.name: t for t in (_GEN_MONO, _GEN_DI, _GEN_COND)}
register(TEMPLATES)
