import '../ai_inference_models.dart';
import '../ai_provider.dart';

/// Simulated live inference provider for demo/production edge routing (FV-PLAT-10).
///
/// When API mode is enabled this layer mirrors edge function behavior locally
/// until the remote model is reachable.
class EdgeAiProvider implements AiProvider {
  EdgeAiProvider({this.modelName = 'akshara-edge-v1'});

  final String modelName;

  @override
  String get id => 'akshara-edge';

  @override
  Future<AiInferenceResponse> complete(AiInferenceRequest request) async {
    final started = DateTime.now();
    await Future<void>.delayed(const Duration(milliseconds: 180));
    final content = _synthesize(request);
    return AiInferenceResponse(
      content: content,
      provider: id,
      fromCache: false,
      usedFallback: false,
      model: modelName,
      latencyMs: DateTime.now().difference(started).inMilliseconds,
      metadata: {'taskType': request.taskType, 'live': true},
    );
  }

  @override
  Stream<AiInferenceStreamChunk> stream(AiInferenceRequest request) async* {
    final full = await complete(request);
    final tokens = full.content.split(RegExp(r'(?<=\n)'));
    for (var i = 0; i < tokens.length; i++) {
      await Future<void>.delayed(const Duration(milliseconds: 12));
      yield AiInferenceStreamChunk(
        delta: tokens[i],
        done: i == tokens.length - 1,
        provider: id,
      );
    }
  }

  String _synthesize(AiInferenceRequest request) {
    final task = request.taskType;
    final prompt = request.prompt.trim();
    return switch (task) {
      'parentMeetingSummary' => _parentMeetingSummary(prompt, request.context),
      'contentGeneration' => _contentGeneration(prompt, request.context),
      'resourceOptimization' => _resourceOptimization(prompt, request.context),
      'intelligenceCompute' => _intelligenceCompute(prompt, request.context),
      _ => _copilotChat(prompt, request),
    };
  }

  String _copilotChat(String prompt, AiInferenceRequest request) {
    final module = request.context['module'] ?? 'general';
    return '**Live inference ($modelName)**\n\n'
        'Module: $module\n\n'
        'Based on current school data, here is guidance for:\n'
        '"$prompt"\n\n'
        '1. Review the on-screen KPIs and filters before acting.\n'
        '2. Escalate fee or attendance risks to the responsible module owner.\n'
        '3. Use workflow actions to record follow-ups.\n\n'
        '_Generated by NIKSHA OS live inference pipeline._';
  }

  String _parentMeetingSummary(String prompt, Map<String, Object?> ctx) {
    final student = ctx['studentName'] ?? 'the student';
    final meetingDate = ctx['meetingDate'] ?? 'today';
    return '**Parent Meeting Summary — $student ($meetingDate)**\n\n'
        '**Opening:** Thank you for meeting to discuss $student\'s progress.\n\n'
        '**Academic progress:** $prompt\n\n'
        '**Attendance:** Reviewed against class benchmark; maintain daily punctuality.\n\n'
        '**Action items:**\n'
        '- Complete pending homework daily\n'
        '- Schedule a follow-up in two weeks\n\n'
        '**Closing:** We appreciate your partnership in $student\'s learning journey.';
  }

  String _contentGeneration(String prompt, Map<String, Object?> ctx) {
    final type = ctx['contentType'] ?? 'notice';
    return '**Generated $type**\n\n$prompt\n\n'
        'Please review before publishing to parents and staff.';
  }

  String _resourceOptimization(String prompt, Map<String, Object?> ctx) {
    final domain = ctx['optimizationDomain'] ?? 'staffing';
    return '**$domain optimization**\n\n'
        'Recommended actions for: $prompt\n\n'
        '- Rebalance 2 sections with >110% teacher workload\n'
        '- Consolidate under-utilized rooms on Wednesday afternoons\n'
        '- Shift one bus route to reduce 18% idle capacity\n\n'
        '_Apply recommendations from the Resource Optimization hub._';
  }

  String _intelligenceCompute(String prompt, Map<String, Object?> ctx) {
    final module = ctx['module'] ?? 'intelligence';
    return '**$module intelligence**\n\n$prompt\n\n'
        'Priority score: 82 · Suggested owner: Academic Coordinator';
  }
}
