/** Server RBAC route inventory — permission + scope requirements for protected API routes. */
export type RbacScope = "school" | "organization" | "parent" | "student";

export interface RbacRouteRule {
  method: string;
  path: string;
  permission: string | null;
  scope: RbacScope;
  module: string;
}

export const RBAC_ROUTE_INVENTORY: RbacRouteRule[] = [
  { method: "GET", path: "/admissions/dashboard", permission: "viewAdmissions", scope: "school", module: "admissions" },
  { method: "POST", path: "/admissions/leads", permission: "manageAdmissions", scope: "school", module: "admissions" },
  { method: "POST", path: "/admissions/documents/upload/presign", permission: "manageAdmissions", scope: "school", module: "admissions" },
  { method: "POST", path: "/admissions/documents/upload", permission: "manageAdmissions", scope: "school", module: "admissions" },
  { method: "GET", path: "/admissions/documents/:id/download", permission: "viewAdmissions", scope: "school", module: "admissions" },
  { method: "POST", path: "/admissions/approvals/:id/approve", permission: "approveAdmissions", scope: "school", module: "admissions" },
  // Admissions completion (B1 unblocked items).
  { method: "POST", path: "/admissions/settings", permission: "manageAdmissions", scope: "school", module: "admissions" },
  { method: "POST", path: "/admissions/leads/bulk", permission: "manageAdmissions", scope: "school", module: "admissions" },
  { method: "GET", path: "/admissions/leads/check-duplicate", permission: "viewAdmissions", scope: "school", module: "admissions" },
  { method: "PATCH", path: "/admissions/leads/:id/lost", permission: "manageAdmissions", scope: "school", module: "admissions" },
  { method: "POST", path: "/admissions/leads/:id/followups/:followupId/complete", permission: "manageAdmissions", scope: "school", module: "admissions" },
  { method: "POST", path: "/admissions/leads/:id/followups/:followupId/reschedule", permission: "manageAdmissions", scope: "school", module: "admissions" },
  { method: "GET", path: "/admissions/enrollments/:id/offer-letter", permission: "viewAdmissions", scope: "school", module: "admissions" },
  // #4: fee-handoff picker options (cross-module read of Finance's catalog).
  { method: "GET", path: "/admissions/fee-structures", permission: "viewAdmissions", scope: "school", module: "admissions" },
  { method: "GET", path: "/finance/dashboard", permission: "viewFinance", scope: "school", module: "finance" },
  { method: "POST", path: "/finance/fee-structures", permission: "manageFinance", scope: "school", module: "finance" },
  { method: "POST", path: "/finance/refunds/:id/approve", permission: "approveRefunds", scope: "school", module: "finance" },
  { method: "GET", path: "/sis/dashboard", permission: "viewSis", scope: "school", module: "sis" },
  { method: "POST", path: "/sis/students", permission: "manageSis", scope: "school", module: "sis" },
  { method: "GET", path: "/sis/transfers", permission: "viewSis", scope: "school", module: "sis" },
  // #5 — admissions-conversion read (the queue the conversion screen loads).
  { method: "GET", path: "/sis/admissions-conversion", permission: "viewSis", scope: "school", module: "sis" },
  { method: "PATCH", path: "/sis/students/:id/documents/:docId/verify", permission: "manageSis", scope: "school", module: "sis" },
  // SIS-4 — read-only siblings / family list for a student (clerk view).
  { method: "GET", path: "/sis/students/:id/siblings", permission: "viewSis", scope: "school", module: "sis" },
  // SIS-1 certificate issuance register + SIS-D1 transfer-certificate (TC) engine.
  { method: "GET", path: "/sis/students/:id/certificates", permission: "viewSis", scope: "school", module: "sis" },
  { method: "POST", path: "/sis/students/:id/certificates", permission: "manageSis", scope: "school", module: "sis" },
  { method: "POST", path: "/sis/students/:id/transfer-certificate", permission: "manageSis", scope: "school", module: "sis" },
  { method: "GET", path: "/academic/years", permission: "viewSis", scope: "school", module: "academic" },
  { method: "POST", path: "/academic/transitions/preview", permission: "manageSis", scope: "school", module: "academic" },
  { method: "POST", path: "/academic/transitions/:id/execute", permission: "manageSis", scope: "school", module: "academic" },
  // Smart Timetable — persisted substitutions (roadmap gap #8).
  { method: "POST", path: "/academic/timetables/substitutions", permission: "manageTimetableSubstitution", scope: "school", module: "academic" },
  { method: "GET", path: "/academic/timetables/substitutions", permission: "viewAcademicTimetable", scope: "school", module: "academic" },
  { method: "GET", path: "/academic/timetables/substitutions/candidates", permission: "viewAcademicTimetable", scope: "school", module: "academic" },
  { method: "DELETE", path: "/academic/timetables/substitutions/:id", permission: "manageTimetableSubstitution", scope: "school", module: "academic" },
  // Smart Timetable — unified per-teacher workload rollup (roadmap gap #9).
  { method: "GET", path: "/academic/timetables/workload/rollup", permission: "viewAcademicTimetable", scope: "school", module: "academic" },
  { method: "GET", path: "/transport/dashboard", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/attendance", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/notify-delay", permission: "manageTransport", scope: "school", module: "transport" },
  // ─── Transport TRN-1..9 (writes = manageTransport, reads = viewTransport) ───
  { method: "GET", path: "/transport/routes", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "GET", path: "/transport/vehicles", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "GET", path: "/transport/drivers", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "GET", path: "/transport/allocations", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "GET", path: "/transport/attendance", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "GET", path: "/transport/tracking", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "GET", path: "/transport/reports", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "GET", path: "/transport/settings", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "GET", path: "/transport/occupancy-metrics", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "GET", path: "/transport/routes/:id/roster", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/routes", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/routes/:id/activate", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/routes/:id/stops", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/routes/:id/stops/reorder", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "PUT", path: "/transport/routes/:id/stops/:stopId", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "DELETE", path: "/transport/routes/:id/stops/:stopId", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/vehicles", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "PUT", path: "/transport/vehicles/:id", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "DELETE", path: "/transport/vehicles/:id", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/drivers", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "PUT", path: "/transport/drivers/:id", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "DELETE", path: "/transport/drivers/:id", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/allocations", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/allocations/bulk", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/allocations/:id/transfer", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "DELETE", path: "/transport/allocations/:id", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/reminders/document-expiry", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "POST", path: "/transport/demands", permission: "manageTransport", scope: "school", module: "transport" },
  { method: "GET", path: "/hr/dashboard", permission: "viewHr", scope: "school", module: "hr" },
  { method: "GET", path: "/hostel/dashboard", permission: "viewHostel", scope: "school", module: "hostel" },
  { method: "POST", path: "/hostel/attendance", permission: "manageHostel", scope: "school", module: "hostel" },
  { method: "POST", path: "/hostel/mess", permission: "manageHostel", scope: "school", module: "hostel" },
  { method: "GET", path: "/library/dashboard", permission: "viewLibrary", scope: "school", module: "library" },
  { method: "GET", path: "/library/overdue", permission: "viewLibrary", scope: "school", module: "library" },
  { method: "GET", path: "/library/settings", permission: "viewLibrary", scope: "school", module: "library" },
  { method: "POST", path: "/library/members", permission: "manageLibrary", scope: "school", module: "library" },
  { method: "POST", path: "/library/fines/:id/waive", permission: "manageLibrary", scope: "school", module: "library" },
  { method: "POST", path: "/library/catalog/import", permission: "manageLibrary", scope: "school", module: "library" },
  { method: "POST", path: "/library/issues/:id/renew", permission: "manageLibrary", scope: "school", module: "library" },
  { method: "POST", path: "/library/reminders/overdue", permission: "manageLibrary", scope: "school", module: "library" },
  { method: "PUT", path: "/library/catalog/:id", permission: "manageLibrary", scope: "school", module: "library" },
  { method: "PUT", path: "/library/settings", permission: "manageLibrary", scope: "school", module: "library" },
  { method: "DELETE", path: "/library/catalog/:id", permission: "manageLibrary", scope: "school", module: "library" },
  { method: "GET", path: "/inventory/dashboard", permission: "viewInventory", scope: "school", module: "inventory" },
  { method: "GET", path: "/inventory/intelligence/copilot", permission: "viewInventoryIntelligence", scope: "school", module: "inventory" },
  { method: "GET", path: "/inventory/intelligence/lifecycle", permission: "viewInventoryIntelligence", scope: "school", module: "inventory" },
  { method: "POST", path: "/inventory/intelligence/lifecycle/events", permission: "manageAssetLifecycle", scope: "school", module: "inventory" },
  { method: "GET", path: "/inventory/intelligence/procurement-workflow", permission: "viewInventoryIntelligence", scope: "school", module: "inventory" },
  { method: "POST", path: "/inventory/intelligence/procurement-workflow/:id/advance", permission: "manageProcurementWorkflow", scope: "school", module: "inventory" },
  { method: "GET", path: "/alumni/dashboard", permission: "viewAlumni", scope: "school", module: "alumni" },
  { method: "POST", path: "/alumni/donations", permission: "manageAlumni", scope: "school", module: "alumni" },
  { method: "GET", path: "/management/dashboard", permission: "viewManagement", scope: "school", module: "management" },
  // PRI-1 — Approval Center batch decide. viewManagement is the REACHABILITY
  // gate only; per-item type-specific approve permission + scope + SoD govern
  // each id's actual authority (a lacking type is skipped, not a blanket 403).
  { method: "POST", path: "/approvals/batch-decide", permission: "viewManagement", scope: "school", module: "approvals" },
  { method: "GET", path: "/control-center/dashboard", permission: "viewControlCenter", scope: "organization", module: "control_center" },
  { method: "GET", path: "/parent/dashboard", permission: null, scope: "parent", module: "parent" },
  // PAR-D3 — annual / 80C fee-payment certificate DATA. Persona-scoped (no
  // permission slug); own-child ownership is enforced server-side against the
  // caller's JWT child_ids plus the finance_receipts/collections parent RLS.
  { method: "GET", path: "/parent/fee-certificate", permission: null, scope: "parent", module: "parent" },
  { method: "POST", path: "/parent/payments/initiate", permission: null, scope: "parent", module: "parent" },
  { method: "POST", path: "/parent/payments/confirm", permission: null, scope: "parent", module: "parent" },
  { method: "POST", path: "/payments/intents/initiate", permission: null, scope: "parent", module: "payment" },
  { method: "POST", path: "/payments/intents/confirm", permission: null, scope: "parent", module: "payment" },
  { method: "GET", path: "/payments/intents/:id", permission: "viewPayments", scope: "school", module: "payment" },
  { method: "GET", path: "/teacher/dashboard", permission: "viewAdminHub", scope: "school", module: "teacher" },
  { method: "POST", path: "/teacher/homework", permission: "manageHomework", scope: "school", module: "teacher" },
  { method: "POST", path: "/teacher/homework/submissions/:id/review", permission: "manageHomework", scope: "school", module: "teacher" },
  { method: "POST", path: "/teacher/attendance/draft", permission: "markAttendance", scope: "school", module: "teacher" },
  { method: "POST", path: "/teacher/attendance/submit", permission: "markAttendance", scope: "school", module: "teacher" },
  { method: "PUT", path: "/teacher/exams/marks/:id", permission: "manageExamMarks", scope: "school", module: "teacher" },
  { method: "POST", path: "/parent/attendance/corrections", permission: null, scope: "parent", module: "attendance" },
  // Parent leave: submit + PAR-D1 cancel + PAR-3 attachment. Persona-scoped (no
  // permission slug); own-child ownership is enforced server-side against the
  // caller's JWT child_ids and the mobile_leave_requests RLS parent policy.
  { method: "POST", path: "/parent/leave", permission: null, scope: "parent", module: "parent" },
  { method: "POST", path: "/parent/leave/:id/cancel", permission: null, scope: "parent", module: "parent" },
  { method: "POST", path: "/parent/leave/:id/attachment", permission: null, scope: "parent", module: "parent" },
  { method: "POST", path: "/staff-attendance/check", permission: "markStaffAttendance", scope: "school", module: "staff_attendance" },
  // TCH-9: read-only SELF attendance history — same universal staff self-service gate as /check.
  { method: "GET", path: "/staff-attendance/my-history", permission: "markStaffAttendance", scope: "school", module: "staff_attendance" },
  { method: "GET", path: "/student/dashboard", permission: null, scope: "student", module: "student" },
  { method: "POST", path: "/audit/events/batch", permission: null, scope: "school", module: "audit" },
  { method: "GET", path: "/communications/templates", permission: "viewCommunications", scope: "school", module: "communication" },
  { method: "POST", path: "/communications/templates", permission: "sendBroadcast", scope: "school", module: "communication" },
  { method: "PUT", path: "/communications/templates/:id", permission: "sendBroadcast", scope: "school", module: "communication" },
  { method: "GET", path: "/communications/broadcasts/history", permission: "sendBroadcast", scope: "school", module: "communication" },
  { method: "GET", path: "/communications/broadcasts/:id/report", permission: "sendBroadcast", scope: "school", module: "communication" },
  { method: "POST", path: "/communications/broadcasts/:id/resend", permission: "sendBroadcast", scope: "school", module: "communication" },
  { method: "POST", path: "/communications/broadcasts", permission: "sendBroadcast", scope: "school", module: "communication" },
  // COM-2: saved audience segments (view=read gate, create/delete=send gate).
  { method: "GET", path: "/communications/audience-segments", permission: "viewCommunications", scope: "school", module: "communication" },
  { method: "POST", path: "/communications/audience-segments", permission: "sendBroadcast", scope: "school", module: "communication" },
  { method: "DELETE", path: "/communications/audience-segments/:id", permission: "sendBroadcast", scope: "school", module: "communication" },
  // COM-D1: acknowledge a delivery (signed receipt). Recipient-owned, like
  // mark-read — no permission slug; the recipient RLS policy enforces ownership.
  { method: "POST", path: "/communications/notifications/:id/acknowledge", permission: null, scope: "parent", module: "communication" },
  { method: "GET", path: "/parent/notifications", permission: null, scope: "parent", module: "communication" },
  { method: "GET", path: "/student/notifications", permission: null, scope: "student", module: "communication" },
  { method: "GET", path: "/education/question-bank", permission: "viewEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/question-bank", permission: "manageEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/question-papers/generate", permission: "manageEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/question-papers/:id/review", permission: "approveEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/question-papers/:id/publish", permission: "approveEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/homework/generate", permission: "manageEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/report-remarks/generate", permission: "manageEducation", scope: "school", module: "education" },
  { method: "GET", path: "/intelligence/risk/students", permission: "viewStudentRisk", scope: "school", module: "intelligence" },
  { method: "POST", path: "/intelligence/risk/students/compute", permission: "generateIntelligence", scope: "school", module: "intelligence" },
  { method: "POST", path: "/intelligence/communication/generate", permission: "generateIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/principal/center", permission: "viewAnalytics", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/principal/query", permission: "viewAnalytics", scope: "school", module: "intelligence" },
  { method: "POST", path: "/intelligence/parent-guidance/:id/publish", permission: "generateIntelligence", scope: "school", module: "intelligence" },
  { method: "POST", path: "/setup-wizard/sessions", permission: "manageSchoolSetup", scope: "school", module: "setup_wizard" },
  { method: "GET", path: "/widgets/registry", permission: "viewDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "PUT", path: "/widgets/dashboard/layout", permission: "manageDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "GET", path: "/widgets/data-sources", permission: "viewDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "GET", path: "/widgets/layouts/versions", permission: "viewDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "GET", path: "/widgets/layouts/:role", permission: "viewDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "PUT", path: "/widgets/layouts/:role", permission: "manageDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "POST", path: "/widgets/layouts/:role/reset", permission: "manageDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "GET", path: "/teacher-assistant/insights", permission: "viewTeacherAssistant", scope: "school", module: "teacher_assistant" },
  { method: "POST", path: "/teacher-assistant/interventions", permission: "manageTeacherAssistant", scope: "school", module: "teacher_assistant" },
  { method: "POST", path: "/parent-insights/generate", permission: "viewParentInsights", scope: "parent", module: "parent_insights" },
  { method: "GET", path: "/parent-insights/students/:studentId", permission: "viewParentInsights", scope: "parent", module: "parent_insights" },
  { method: "GET", path: "/principal-command/center", permission: "viewPrincipalCommand", scope: "school", module: "principal_command" },
  { method: "GET", path: "/growth/dashboard", permission: "viewGrowthPlatform", scope: "school", module: "growth" },
  { method: "POST", path: "/growth/campaigns", permission: "manageGrowthPlatform", scope: "school", module: "growth" },
  { method: "GET", path: "/intelligence/homework-intelligence/plan", permission: "viewHomeworkIntelligence", scope: "school", module: "intelligence" },
  { method: "POST", path: "/intelligence/homework-intelligence/generate", permission: "manageHomeworkIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/student-success/dashboard", permission: "viewStudentSuccessIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/student-success/predictions", permission: "viewStudentSuccessIntelligence", scope: "school", module: "intelligence" },
  { method: "POST", path: "/intelligence/student-success/compute", permission: "generateIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/student-success/improvements", permission: "viewStudentSuccessIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/student-success/interventions", permission: "viewStudentSuccessIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/student-success/students/:id", permission: "viewStudentSuccessIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/analytics", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/subject-performance", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/weak-chapters", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/result-intelligence", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/forecast", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/rank-movement", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/sis/students/:id/360", permission: "viewStudent360", scope: "school", module: "sis" },
  { method: "GET", path: "/employees/dashboard", permission: "viewEmployees", scope: "school", module: "employee" },
  { method: "POST", path: "/employees/:id/roles", permission: "manageEmployees", scope: "school", module: "employee" },
  // ─── INV-1..7: Store stock module (writes = manageInventory, reads = viewInventory) ───
  { method: "POST", path: "/inventory/stock/issue", permission: "manageInventory", scope: "school", module: "inventory" },
  { method: "POST", path: "/inventory/stock/adjust", permission: "manageInventory", scope: "school", module: "inventory" },
  { method: "POST", path: "/inventory/stock/adjustments/:id/approve", permission: "manageInventory", scope: "school", module: "inventory" },
  { method: "POST", path: "/inventory/stock/adjustments/:id/reject", permission: "manageInventory", scope: "school", module: "inventory" },
  { method: "GET", path: "/inventory/stock/adjustments", permission: "viewInventory", scope: "school", module: "inventory" },
  { method: "POST", path: "/inventory/stock/count", permission: "manageInventory", scope: "school", module: "inventory" },
  { method: "GET", path: "/inventory/stock/items", permission: "viewInventory", scope: "school", module: "inventory" },
  { method: "POST", path: "/inventory/stock/items", permission: "manageInventory", scope: "school", module: "inventory" },
  { method: "PUT", path: "/inventory/stock/items", permission: "manageInventory", scope: "school", module: "inventory" },
  { method: "GET", path: "/inventory/stock/register", permission: "viewInventory", scope: "school", module: "inventory" },
  { method: "GET", path: "/inventory/stock/low-stock", permission: "viewInventory", scope: "school", module: "inventory" },
  { method: "POST", path: "/inventory/distribution/items", permission: "manageInventoryDistribution", scope: "school", module: "inventory_distribution" },
  { method: "GET", path: "/inventory/distribution/reports", permission: "viewInventoryDistribution", scope: "school", module: "inventory_distribution" },
  { method: "GET", path: "/inventory/distribution/dashboard", permission: "viewInventoryDistribution", scope: "school", module: "inventory_distribution" },
  { method: "GET", path: "/inventory/distribution/replacements", permission: "viewInventoryDistribution", scope: "school", module: "inventory_distribution" },
  { method: "POST", path: "/inventory/distribution/replacements/:id/approve", permission: "manageInventoryDistribution", scope: "school", module: "inventory_distribution" },
  { method: "POST", path: "/inventory/distribution/replacements/:id/fulfill", permission: "manageInventoryDistribution", scope: "school", module: "inventory_distribution" },
  { method: "POST", path: "/inventory/distribution/replacements/:id/reject", permission: "manageInventoryDistribution", scope: "school", module: "inventory_distribution" },
  { method: "GET", path: "/parent/experience/hub", permission: "viewParentExperience", scope: "parent", module: "parent" },
  { method: "POST", path: "/parent/experience/acknowledge", permission: "viewParentExperience", scope: "parent", module: "parent" },
  { method: "GET", path: "/employees/:id/360", permission: "viewEmployeeIntelligence", scope: "school", module: "employee" },
  { method: "GET", path: "/employees/intelligence/dashboard", permission: "viewEmployeeIntelligence", scope: "school", module: "employee" },
  { method: "GET", path: "/operations/hub", permission: "viewOperationsHub", scope: "school", module: "operations" },
  { method: "GET", path: "/memories/events", permission: "viewSchoolMemories", scope: "school", module: "memories" },
  { method: "POST", path: "/memories/events", permission: "manageSchoolMemories", scope: "school", module: "memories" },
  { method: "GET", path: "/memories/analytics", permission: "viewSchoolMemories", scope: "school", module: "memories" },
  { method: "GET", path: "/memories/events/:id", permission: "viewSchoolMemories", scope: "school", module: "memories" },
  { method: "POST", path: "/memories/events/:id/publish", permission: "manageSchoolMemories", scope: "school", module: "memories" },
  { method: "POST", path: "/memories/events/:id/upload/presign", permission: "manageSchoolMemories", scope: "school", module: "memories" },
  { method: "POST", path: "/memories/events/:id/upload/confirm", permission: "manageSchoolMemories", scope: "school", module: "memories" },
  { method: "GET", path: "/memories/media/:id/download", permission: "viewSchoolMemories", scope: "school", module: "memories" },
  { method: "GET", path: "/memories/share/:token", permission: "viewSchoolMemories", scope: "school", module: "memories" },
  { method: "GET", path: "/promotions", permission: "viewAchievementPromotion", scope: "school", module: "promotion" },
  { method: "POST", path: "/promotions", permission: "manageAchievementPromotion", scope: "school", module: "promotion" },
  { method: "POST", path: "/promotions/:id/generate", permission: "manageAchievementPromotion", scope: "school", module: "promotion" },
  { method: "POST", path: "/promotions/:id/approve", permission: "approveAchievementPromotion", scope: "school", module: "promotion" },
  { method: "POST", path: "/promotions/:id/publish", permission: "approveAchievementPromotion", scope: "school", module: "promotion" },
  { method: "POST", path: "/promotions/:id/track", permission: "manageAchievementPromotion", scope: "school", module: "promotion" },
  { method: "GET", path: "/school-calendar", permission: "viewSchoolCalendar", scope: "school", module: "school_calendar" },
  { method: "POST", path: "/school-calendar", permission: "manageSchoolCalendar", scope: "school", module: "school_calendar" },
  { method: "DELETE", path: "/school-calendar/:id", permission: "manageSchoolCalendar", scope: "school", module: "school_calendar" },
  { method: "POST", path: "/social/connect/start", permission: "manageSocialConnections", scope: "school", module: "social" },
  { method: "POST", path: "/social/connect/complete", permission: "manageSocialConnections", scope: "school", module: "social" },
  { method: "GET", path: "/social/connections", permission: "viewSocialConnections", scope: "school", module: "social" },
  { method: "DELETE", path: "/social/connections/:id", permission: "manageSocialConnections", scope: "school", module: "social" },
  { method: "GET", path: "/onboarding/dashboard", permission: "viewOnboarding", scope: "school", module: "onboarding" },
  { method: "GET", path: "/onboarding/imports", permission: "viewOnboarding", scope: "school", module: "onboarding" },
  { method: "GET", path: "/onboarding/imports/:id", permission: "viewOnboarding", scope: "school", module: "onboarding" },
  { method: "POST", path: "/onboarding/imports/students/preview", permission: "manageOnboarding", scope: "school", module: "onboarding" },
  { method: "POST", path: "/onboarding/imports/teachers/preview", permission: "manageOnboarding", scope: "school", module: "onboarding" },
  { method: "POST", path: "/onboarding/imports/:id/commit", permission: "manageOnboarding", scope: "school", module: "onboarding" },
  { method: "POST", path: "/onboarding/imports/:id/rollback", permission: "manageOnboarding", scope: "school", module: "onboarding" },
  { method: "GET", path: "/onboarding/invites", permission: "viewOnboarding", scope: "school", module: "onboarding" },
  { method: "POST", path: "/onboarding/invites", permission: "manageOnboarding", scope: "school", module: "onboarding" },

  // ─── Wave 3: finance peripheral routes (STF-1..5) ───────────────────────────
  { method: "GET", path: "/finance/discounts", permission: "viewFinance", scope: "school", module: "finance" },
  { method: "POST", path: "/finance/payments/offline", permission: "manageFinance", scope: "school", module: "finance" },
  { method: "GET", path: "/finance/payments/offline", permission: "viewFinance", scope: "school", module: "finance" },
  { method: "POST", path: "/finance/payments/offline/:id/reconcile", permission: "manageFinance", scope: "school", module: "finance" },
  { method: "POST", path: "/finance/payments/qr", permission: "manageFinance", scope: "school", module: "finance" },
  { method: "GET", path: "/finance/payments/qr/:id", permission: "viewFinance", scope: "school", module: "finance" },
  { method: "POST", path: "/finance/payments/qr/:id/confirm", permission: "manageFinance", scope: "school", module: "finance" },
  { method: "GET", path: "/finance/defaulters", permission: "viewFinance", scope: "school", module: "finance" },
  { method: "GET", path: "/finance/reports", permission: "viewFinance", scope: "school", module: "finance" },
  { method: "GET", path: "/finance/settings", permission: "viewFinance", scope: "school", module: "finance" },
  { method: "PUT", path: "/finance/settings", permission: "manageFinance", scope: "school", module: "finance" },
  { method: "POST", path: "/finance/scholarships", permission: "manageFinance", scope: "school", module: "finance" },
  { method: "PUT", path: "/finance/scholarships/:id", permission: "manageFinance", scope: "school", module: "finance" },

  // ─── Wave 3 (SEC-6): previously-unmapped live routers ───────────────────────
  // Predictions (additionally Enterprise feature.ai_predictions gated at runtime).
  { method: "GET", path: "/predictions/fee-defaults", permission: "viewFinance", scope: "school", module: "predictions" },
  { method: "GET", path: "/predictions/student-risk", permission: "viewStudentRisk", scope: "school", module: "predictions" },
  // Director portal (org-scope multi-school aggregation).
  { method: "GET", path: "/director/summary", permission: "viewDirectorPortal", scope: "organization", module: "director" },
  { method: "POST", path: "/director/metric-inputs", permission: "manageDirectorPortal", scope: "organization", module: "director" },
  // DIR-2 — consolidated collection report (per-school fee%/billed/collected/outstanding + org totals).
  { method: "GET", path: "/director/collections", permission: "viewDirectorPortal", scope: "organization", module: "director" },
  // DIR-D1 — audited read-only per-school drill-down ("Open Management Portal").
  { method: "GET", path: "/director/schools/:schoolId/snapshot", permission: "viewDirectorPortal", scope: "organization", module: "director" },
  // Organization builder (Enterprise feature.organization_builder gated at runtime).
  { method: "GET", path: "/platform/org-builder/packs", permission: "viewOrganizationBuilder", scope: "organization", module: "organization_builder" },
  { method: "POST", path: "/platform/org-builder/provision", permission: "manageOrganizationBuilder", scope: "organization", module: "organization_builder" },
  // Entitlements / subscription plan catalog + assignment.
  { method: "GET", path: "/subscription", permission: "viewSubscription", scope: "school", module: "subscriptions" },
  { method: "PUT", path: "/platform/organizations/:id/subscription", permission: "managePlatformSubscriptions", scope: "organization", module: "subscriptions" },
  // Dynamic widget platform role layouts (RBAC-only, no entitlement gate).
  { method: "PUT", path: "/widgets/layouts/:role", permission: "manageDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "POST", path: "/widgets/layouts/:role/reset", permission: "manageDynamicWidgets", scope: "school", module: "widget_platform" },
  // Webhooks are authenticated by shared-secret HMAC over the raw body, NOT by a
  // JWT/permission — listed here for inventory completeness (permission: null).
  { method: "POST", path: "/communications/delivery/webhook", permission: null, scope: "school", module: "webhook" },
  { method: "POST", path: "/webhooks/razorpay", permission: null, scope: "school", module: "webhook" },
];

export const RBAC_MODULE_PERMISSIONS = [
  "viewAdmissions", "manageAdmissions", "approveAdmissions",
  "viewFinance", "manageFinance", "approveRefunds",
  "viewSis", "manageSis",
  "viewTransport", "viewHr", "viewHostel", "viewLibrary", "viewInventory", "viewAlumni", "manageAlumni",
  "viewManagement", "viewControlCenter", "viewAdminHub", "viewPayments",
  "viewCommunications", "manageCommunications", "sendBroadcast",
  "viewEducation", "manageEducation", "approveEducation",
  "viewStudentRisk", "generateIntelligence",
  "viewHomeworkIntelligence", "manageHomeworkIntelligence",
  "viewStudentSuccessIntelligence", "viewExamIntelligence",
  "viewStudent360", "viewEmployees", "manageEmployees",
  "viewInventoryDistribution", "manageInventoryDistribution",
  "viewInventoryIntelligence", "manageAssetLifecycle", "manageProcurementWorkflow",
  "viewParentExperience", "viewEmployeeIntelligence", "viewOperationsHub",
  "viewSchoolMemories", "manageSchoolMemories",
  "viewAchievementPromotion", "manageAchievementPromotion", "approveAchievementPromotion",
  "viewOnboarding", "manageOnboarding",
  "viewSubscription", "managePlatformSubscriptions",
  "viewDirectorPortal", "manageDirectorPortal",
  "viewOrganizationBuilder", "manageOrganizationBuilder",
  "viewDynamicWidgets", "manageDynamicWidgets",
] as const;
