/** Server RBAC route inventory — permission + scope requirements for protected API routes. */
export type RbacScope = "school" | "organization" | "parent" | "student";

export interface RbacRouteRule {
  method: string;
  path: string;
  permission: string | null;
  scope: RbacScope;
  module: string;
}

export const RBAC_ROUTE_INVENTORY: RbacRouteRule[] = [
  { method: "GET", path: "/admissions/dashboard", permission: "viewAdmissions", scope: "school", module: "admissions" },
  { method: "POST", path: "/admissions/leads", permission: "manageAdmissions", scope: "school", module: "admissions" },
  { method: "POST", path: "/admissions/approvals/:id/approve", permission: "approveAdmissions", scope: "school", module: "admissions" },
  { method: "GET", path: "/finance/dashboard", permission: "viewFinance", scope: "school", module: "finance" },
  { method: "POST", path: "/finance/fee-structures", permission: "manageFinance", scope: "school", module: "finance" },
  { method: "POST", path: "/finance/refunds/:id/approve", permission: "approveRefunds", scope: "school", module: "finance" },
  { method: "GET", path: "/sis/dashboard", permission: "viewSis", scope: "school", module: "sis" },
  { method: "POST", path: "/sis/students", permission: "manageSis", scope: "school", module: "sis" },
  { method: "GET", path: "/academic/years", permission: "viewSis", scope: "school", module: "academic" },
  { method: "POST", path: "/academic/transitions/preview", permission: "manageSis", scope: "school", module: "academic" },
  { method: "POST", path: "/academic/transitions/:id/execute", permission: "manageSis", scope: "school", module: "academic" },
  { method: "GET", path: "/transport/dashboard", permission: "viewTransport", scope: "school", module: "transport" },
  { method: "GET", path: "/hr/dashboard", permission: "viewHr", scope: "school", module: "hr" },
  { method: "GET", path: "/hostel/dashboard", permission: "viewHostel", scope: "school", module: "hostel" },
  { method: "GET", path: "/library/dashboard", permission: "viewLibrary", scope: "school", module: "library" },
  { method: "GET", path: "/inventory/dashboard", permission: "viewInventory", scope: "school", module: "inventory" },
  { method: "GET", path: "/inventory/intelligence/copilot", permission: "viewInventoryIntelligence", scope: "school", module: "inventory" },
  { method: "GET", path: "/inventory/intelligence/lifecycle", permission: "viewInventoryIntelligence", scope: "school", module: "inventory" },
  { method: "POST", path: "/inventory/intelligence/lifecycle/events", permission: "manageAssetLifecycle", scope: "school", module: "inventory" },
  { method: "GET", path: "/inventory/intelligence/procurement-workflow", permission: "viewInventoryIntelligence", scope: "school", module: "inventory" },
  { method: "POST", path: "/inventory/intelligence/procurement-workflow/:id/advance", permission: "manageProcurementWorkflow", scope: "school", module: "inventory" },
  { method: "GET", path: "/alumni/dashboard", permission: "viewAlumni", scope: "school", module: "alumni" },
  { method: "GET", path: "/management/dashboard", permission: "viewManagement", scope: "school", module: "management" },
  { method: "GET", path: "/control-center/dashboard", permission: "viewControlCenter", scope: "organization", module: "control_center" },
  { method: "GET", path: "/parent/dashboard", permission: null, scope: "parent", module: "parent" },
  { method: "POST", path: "/parent/payments/initiate", permission: null, scope: "parent", module: "parent" },
  { method: "POST", path: "/parent/payments/confirm", permission: null, scope: "parent", module: "parent" },
  { method: "POST", path: "/payments/intents/initiate", permission: null, scope: "parent", module: "payment" },
  { method: "POST", path: "/payments/intents/confirm", permission: null, scope: "parent", module: "payment" },
  { method: "GET", path: "/payments/intents/:id", permission: "viewPayments", scope: "school", module: "payment" },
  { method: "GET", path: "/teacher/dashboard", permission: "viewAdminHub", scope: "school", module: "teacher" },
  { method: "POST", path: "/teacher/homework", permission: null, scope: "school", module: "teacher" },
  { method: "GET", path: "/student/dashboard", permission: null, scope: "student", module: "student" },
  { method: "POST", path: "/audit/events/batch", permission: null, scope: "school", module: "audit" },
  { method: "GET", path: "/communications/templates", permission: "viewCommunications", scope: "school", module: "communication" },
  { method: "POST", path: "/communications/broadcasts", permission: "sendBroadcast", scope: "school", module: "communication" },
  { method: "GET", path: "/parent/notifications", permission: null, scope: "parent", module: "communication" },
  { method: "GET", path: "/student/notifications", permission: null, scope: "student", module: "communication" },
  { method: "GET", path: "/education/question-bank", permission: "viewEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/question-bank", permission: "manageEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/question-papers/generate", permission: "manageEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/question-papers/:id/review", permission: "approveEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/question-papers/:id/publish", permission: "approveEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/homework/generate", permission: "manageEducation", scope: "school", module: "education" },
  { method: "POST", path: "/education/report-remarks/generate", permission: "manageEducation", scope: "school", module: "education" },
  { method: "GET", path: "/intelligence/risk/students", permission: "viewStudentRisk", scope: "school", module: "intelligence" },
  { method: "POST", path: "/intelligence/risk/students/compute", permission: "generateIntelligence", scope: "school", module: "intelligence" },
  { method: "POST", path: "/intelligence/communication/generate", permission: "generateIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/principal/center", permission: "viewAnalytics", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/principal/query", permission: "viewAnalytics", scope: "school", module: "intelligence" },
  { method: "POST", path: "/intelligence/parent-guidance/:id/publish", permission: "generateIntelligence", scope: "school", module: "intelligence" },
  { method: "POST", path: "/setup-wizard/sessions", permission: "manageSchoolSetup", scope: "school", module: "setup_wizard" },
  { method: "GET", path: "/widgets/registry", permission: "viewDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "PUT", path: "/widgets/dashboard/layout", permission: "manageDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "GET", path: "/widgets/data-sources", permission: "viewDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "GET", path: "/widgets/layouts/versions", permission: "viewDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "GET", path: "/widgets/layouts/:role", permission: "viewDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "PUT", path: "/widgets/layouts/:role", permission: "manageDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "POST", path: "/widgets/layouts/:role/reset", permission: "manageDynamicWidgets", scope: "school", module: "widget_platform" },
  { method: "GET", path: "/teacher-assistant/insights", permission: "viewTeacherAssistant", scope: "school", module: "teacher_assistant" },
  { method: "POST", path: "/teacher-assistant/interventions", permission: "manageTeacherAssistant", scope: "school", module: "teacher_assistant" },
  { method: "POST", path: "/parent-insights/generate", permission: "viewParentInsights", scope: "parent", module: "parent_insights" },
  { method: "GET", path: "/parent-insights/students/:studentId", permission: "viewParentInsights", scope: "parent", module: "parent_insights" },
  { method: "GET", path: "/principal-command/center", permission: "viewPrincipalCommand", scope: "school", module: "principal_command" },
  { method: "GET", path: "/growth/dashboard", permission: "viewGrowthPlatform", scope: "school", module: "growth" },
  { method: "POST", path: "/growth/campaigns", permission: "manageGrowthPlatform", scope: "school", module: "growth" },
  { method: "GET", path: "/intelligence/homework-intelligence/plan", permission: "viewHomeworkIntelligence", scope: "school", module: "intelligence" },
  { method: "POST", path: "/intelligence/homework-intelligence/generate", permission: "manageHomeworkIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/student-success/dashboard", permission: "viewStudentSuccessIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/student-success/predictions", permission: "viewStudentSuccessIntelligence", scope: "school", module: "intelligence" },
  { method: "POST", path: "/intelligence/student-success/compute", permission: "generateIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/student-success/improvements", permission: "viewStudentSuccessIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/student-success/interventions", permission: "viewStudentSuccessIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/student-success/students/:id", permission: "viewStudentSuccessIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/analytics", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/subject-performance", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/weak-chapters", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/result-intelligence", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/forecast", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/intelligence/exam/rank-movement", permission: "viewExamIntelligence", scope: "school", module: "intelligence" },
  { method: "GET", path: "/sis/students/:id/360", permission: "viewStudent360", scope: "school", module: "sis" },
  { method: "GET", path: "/employees/dashboard", permission: "viewEmployees", scope: "school", module: "employee" },
  { method: "POST", path: "/employees/:id/roles", permission: "manageEmployees", scope: "school", module: "employee" },
  { method: "POST", path: "/inventory/distribution/items", permission: "manageInventoryDistribution", scope: "school", module: "inventory_distribution" },
  { method: "GET", path: "/inventory/distribution/reports", permission: "viewInventoryDistribution", scope: "school", module: "inventory_distribution" },
  { method: "GET", path: "/inventory/distribution/dashboard", permission: "viewInventoryDistribution", scope: "school", module: "inventory_distribution" },
  { method: "GET", path: "/parent/experience/hub", permission: "viewParentExperience", scope: "parent", module: "parent" },
  { method: "POST", path: "/parent/experience/acknowledge", permission: "viewParentExperience", scope: "parent", module: "parent" },
  { method: "GET", path: "/employees/:id/360", permission: "viewEmployeeIntelligence", scope: "school", module: "employee" },
  { method: "GET", path: "/employees/intelligence/dashboard", permission: "viewEmployeeIntelligence", scope: "school", module: "employee" },
  { method: "GET", path: "/operations/hub", permission: "viewOperationsHub", scope: "school", module: "operations" },
  { method: "GET", path: "/memories/events", permission: "viewSchoolMemories", scope: "school", module: "memories" },
  { method: "POST", path: "/memories/events", permission: "manageSchoolMemories", scope: "school", module: "memories" },
  { method: "GET", path: "/memories/analytics", permission: "viewSchoolMemories", scope: "school", module: "memories" },
  { method: "GET", path: "/memories/events/:id", permission: "viewSchoolMemories", scope: "school", module: "memories" },
  { method: "POST", path: "/memories/events/:id/publish", permission: "manageSchoolMemories", scope: "school", module: "memories" },
  { method: "POST", path: "/memories/events/:id/upload/presign", permission: "manageSchoolMemories", scope: "school", module: "memories" },
  { method: "POST", path: "/memories/events/:id/upload/confirm", permission: "manageSchoolMemories", scope: "school", module: "memories" },
  { method: "GET", path: "/memories/media/:id/download", permission: "viewSchoolMemories", scope: "school", module: "memories" },
  { method: "GET", path: "/memories/share/:token", permission: "viewSchoolMemories", scope: "school", module: "memories" },
  { method: "GET", path: "/promotions", permission: "viewAchievementPromotion", scope: "school", module: "promotion" },
  { method: "POST", path: "/promotions", permission: "manageAchievementPromotion", scope: "school", module: "promotion" },
  { method: "POST", path: "/promotions/:id/generate", permission: "manageAchievementPromotion", scope: "school", module: "promotion" },
  { method: "POST", path: "/promotions/:id/approve", permission: "approveAchievementPromotion", scope: "school", module: "promotion" },
  { method: "POST", path: "/promotions/:id/publish", permission: "approveAchievementPromotion", scope: "school", module: "promotion" },
  { method: "POST", path: "/promotions/:id/track", permission: "viewAchievementPromotion", scope: "school", module: "promotion" },
  { method: "GET", path: "/school-calendar", permission: "viewSchoolCalendar", scope: "school", module: "school_calendar" },
  { method: "POST", path: "/school-calendar", permission: "manageSchoolCalendar", scope: "school", module: "school_calendar" },
  { method: "DELETE", path: "/school-calendar/:id", permission: "manageSchoolCalendar", scope: "school", module: "school_calendar" },
  { method: "POST", path: "/social/connect/start", permission: "manageSocialConnections", scope: "school", module: "social" },
  { method: "POST", path: "/social/connect/complete", permission: "manageSocialConnections", scope: "school", module: "social" },
  { method: "GET", path: "/social/connections", permission: "viewSocialConnections", scope: "school", module: "social" },
  { method: "DELETE", path: "/social/connections/:id", permission: "manageSocialConnections", scope: "school", module: "social" },
  { method: "GET", path: "/onboarding/dashboard", permission: "viewOnboarding", scope: "school", module: "onboarding" },
  { method: "GET", path: "/onboarding/imports", permission: "viewOnboarding", scope: "school", module: "onboarding" },
  { method: "GET", path: "/onboarding/imports/:id", permission: "viewOnboarding", scope: "school", module: "onboarding" },
  { method: "POST", path: "/onboarding/imports/students/preview", permission: "manageOnboarding", scope: "school", module: "onboarding" },
  { method: "POST", path: "/onboarding/imports/teachers/preview", permission: "manageOnboarding", scope: "school", module: "onboarding" },
  { method: "POST", path: "/onboarding/imports/:id/commit", permission: "manageOnboarding", scope: "school", module: "onboarding" },
  { method: "POST", path: "/onboarding/imports/:id/rollback", permission: "manageOnboarding", scope: "school", module: "onboarding" },
  { method: "GET", path: "/onboarding/invites", permission: "viewOnboarding", scope: "school", module: "onboarding" },
  { method: "POST", path: "/onboarding/invites", permission: "manageOnboarding", scope: "school", module: "onboarding" },
];

export const RBAC_MODULE_PERMISSIONS = [
  "viewAdmissions", "manageAdmissions", "approveAdmissions",
  "viewFinance", "manageFinance", "approveRefunds",
  "viewSis", "manageSis",
  "viewTransport", "viewHr", "viewHostel", "viewLibrary", "viewInventory", "viewAlumni",
  "viewManagement", "viewControlCenter", "viewAdminHub", "viewPayments",
  "viewCommunications", "manageCommunications", "sendBroadcast",
  "viewEducation", "manageEducation", "approveEducation",
  "viewStudentRisk", "generateIntelligence",
  "viewHomeworkIntelligence", "manageHomeworkIntelligence",
  "viewStudentSuccessIntelligence", "viewExamIntelligence",
  "viewStudent360", "viewEmployees", "manageEmployees",
  "viewInventoryDistribution", "manageInventoryDistribution",
  "viewInventoryIntelligence", "manageAssetLifecycle", "manageProcurementWorkflow",
  "viewParentExperience", "viewEmployeeIntelligence", "viewOperationsHub",
  "viewSchoolMemories", "manageSchoolMemories",
  "viewAchievementPromotion", "manageAchievementPromotion", "approveAchievementPromotion",
  "viewOnboarding", "manageOnboarding",
] as const;
